import '@/styles/globals.css'
import { SessionProvider } from 'next-auth/react'
import { WorkoutProvider } from '@/workoutContext';
import { UserProvider } from '@/userContext';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer, toast } from 'react-toastify';
import BottomNav from '@/components/layout/BottomNav';
import Head from 'next/head';


export default function App({ Component, pageProps }) {
  
  return (
    <SessionProvider session={pageProps.session}>
      <UserProvider>
        <WorkoutProvider>
        <Head>
          <title>Hoyst</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
          <link rel="icon" href="/favicon.ico" />
        </Head>
          <BottomNav>
            <Component {...pageProps}/>
            <ToastContainer />
          </BottomNav>
        </WorkoutProvider>
      </UserProvider>
    </SessionProvider>
  )
}
