import '@/styles/globals.css'
import { SessionProvider } from 'next-auth/react'
import { WorkoutProvider } from '@/workoutContext';
import { UserProvider } from '@/userContext';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer, toast } from 'react-toastify';
import BottomNav from '@/components/layout/BottomNav';
import Head from 'next/head';
import { useEffect } from 'react';


export default function App({ Component, pageProps }) {

  //Start Google Analytics when the app loads
  const initGA = () => {
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments)}
    gtag('js', new Date());
    gtag('config', 'G-VTLDPCH7N8');
  }

  useEffect(() => {
      initGA();
  }, []);
  
  return (
    <SessionProvider session={pageProps.session}>
      <UserProvider>
        <WorkoutProvider>
        <Head>
          <title>Hoyst</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
          <link rel="icon" href="/favicon.ico" />
          <script async src="https://www.googletagmanager.com/gtag/js?id=G-VTLDPCH7N8"></script>
          <script async defer src="https://tools.luckyorange.com/core/lo.js?site-id=5d2495d9"></script>
        </Head>
          <BottomNav>
            <Component {...pageProps}/>
            <ToastContainer />
          </BottomNav>
        </WorkoutProvider>
      </UserProvider>
    </SessionProvider>
  )
}
