import Head from 'next/head'
import { Inter } from 'next/font/google'
import { SignUpWithGoogleButton } from '@/components/Auth'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-gradient-to-bl from-[#ff7418] to-[#f55622] h-screen">
        <div className="max-w-[600px] h-full mx-auto flex flex-col items-center justify-center">
          <h1 className="text-white text-[4rem] font-black">Hoyst</h1>
          <h2 className="text-white text-[2rem] font-bold mb-12">Built by lifters, for lifters</h2>
          <div className="bg-white px-[20px] py-[20px] rounded-full flex items-center justify-center mb-12">
            <img src="hero.png" alt="hero" className="w-[300px]" />
          </div>
          <SignUpWithGoogleButton />
        </div>
      </main>
    </>
  )
}
